services:
  Tardigrades\SectionField\Api\Serializer\SerializeToArray:
    public: false
    arguments:
      - '%kernel.cache_dir%'
      - '@service_container'

  Tardigrades\SectionField\Api\Controller\RestController:
    public: true
    arguments:
      - '@section_field.create.section'
      - '@section_field.read.section'
      - '@section_field.delete.section'
      - '@section_field.form'
      - '@section_field.manager.doctrine.section_manager'
      - '@request_stack'
      - '@event_dispatcher'
      - '@Tardigrades\SectionField\Api\Serializer\SerializeToArray'
      - '@default.cache'
      - '@security.token_storage'

  rest.controller:
    alias: 'Tardigrades\SectionField\Api\Controller\RestController'
    public: true

  Tardigrades\SectionField\Api\Controller\RestInfoController:
    public: true
    arguments:
      - '@section_field.create.section'
      - '@section_field.read.section'
      - '@section_field.delete.section'
      - '@section_field.form'
      - '@section_field.manager.doctrine.section_manager'
      - '@request_stack'
      - '@event_dispatcher'
      - '@Tardigrades\SectionField\Api\Serializer\SerializeToArray'
      - '@default.cache'
      - '@security.token_storage'

  rest.info.controller:
    alias: 'Tardigrades\SectionField\Api\Controller\RestInfoController'
    public: true
