services:
  Tardigrades\SectionField\Api\Serializer\SerializeToArray:
    public: false
    arguments:
      - '%kernel.cache_dir%'

  Tardigrades\SectionField\Api\Controller\RestController:
    public: false
    arguments:
      - '@section_field.create.section'
      - '@section_field.read.section'
      - '@section_field.delete.section'
      - '@section_field.form'
      - '@section_field.manager.doctrine.section_manager'
      - '@request_stack'
      - '@event_dispatcher'
      - '@Tardigrades\SectionField\Api\Serializer\SerializeToArray'

  rest.controller: '@Tardigrades\SectionField\Api\Controller\RestController'     
